import type { Member, Category } from "@/types"

export const sampleMembers: Member[] = [
  {
    id: 1,
    name: "EcoTech Solutions",
    slug: "ecotech-solutions",
    tagline: "Renewable energy for the future",
    description: "Leading provider of solar and wind energy solutions for businesses and communities.",
    logo: "/ecotech-solutions-logo.png",
    coverImage: "/placeholder-b13jp.png",
    location: "San Francisco, CA",
    category: "Energy & Environment",
    tier: "Enterprise",
    rating: 4.9,
    reviews: 127,
    sustainabilityScore: 95,
    certifications: ["B-Corp", "LEED Platinum", "ISO 14001"],
    specialties: ["Solar Installation", "Energy Consulting", "Smart Grid"],
    featured: true,
    verified: true,
  },
  {
    id: 2,
    name: "Green Packaging Co.",
    slug: "green-packaging-co",
    tagline: "Sustainable packaging solutions",
    description: "Innovative biodegradable and compostable packaging for e-commerce and retail.",
    logo: "/green-packaging-co-logo.png",
    coverImage: "/eco-friendly-packaging.png",
    location: "Portland, OR",
    category: "Manufacturing",
    tier: "Premium",
    rating: 4.8,
    reviews: 89,
    sustainabilityScore: 92,
    certifications: ["FSC Certified", "Compostable"],
    specialties: ["Biodegradable Materials", "Custom Design", "Supply Chain"],
    featured: true,
    verified: true,
  },
  {
    id: 3,
    name: "Sustainable Eats",
    tagline: "Farm-to-table dining experience",
    description: "Zero-waste restaurant chain committed to local sourcing and sustainable practices.",
    logo: "/sustainable-eats-logo.png",
    coverImage: "/placeholder.svg?width=400&height=200",
    location: "Austin, TX",
    category: "Food & Beverage",
    tier: "Basic",
    rating: 4.7,
    reviews: 203,
    sustainabilityScore: 88,
    certifications: ["Organic Certified", "Zero Waste"],
    specialties: ["Local Sourcing", "Waste Reduction", "Community Impact"],
    featured: false,
    verified: false,
  },
]

export const categories: Category[] = [
  { id: "all", name: "All Categories", count: 500 },
  { id: "energy", name: "Energy & Environment", count: 89 },
  { id: "manufacturing", name: "Manufacturing", count: 76 },
  { id: "food", name: "Food & Beverage", count: 134 },
  { id: "technology", name: "Technology", count: 98 },
  { id: "consulting", name: "Consulting", count: 67 },
  { id: "transportation", name: "Transportation", count: 36 },
]

export const membershipTiers = [
  {
    name: "Basic",
    price: 29,
    period: "Monthly",
    features: ["Directory Listing", "Basic Profile", "Community Access", "Monthly Newsletter"],
    active: true,
    order: 1,
  },
  {
    name: "Premium",
    price: 59,
    period: "Monthly",
    features: ["Featured Listing", "Enhanced Profile", "Priority Support", "Exclusive Content", "Event Access"],
    active: true,
    order: 2,
  },
  {
    name: "Enterprise",
    price: 99,
    period: "Monthly",
    features: [
      "Spotlight Features",
      "Custom Branding",
      "Analytics Dashboard",
      "Partnership Opportunities",
      "Dedicated Support",
    ],
    active: true,
    order: 3,
  },
]
